package services

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"time"

	"github.com/firecrawl/go-api/models"
	"github.com/google/uuid"
	"github.com/rs/zerolog/log"
)

// LLMsTextService 自动化提取生成站点 llms.txt 服务
type LLMsTextService struct {
	scrapeService *ScrapeService
	redisService  *RedisService
	jobsLock      sync.RWMutex
	jobs          map[string]*models.LLMsTextJob
}

// NewLLMsTextService 初始化 LLMsTextService
func NewLLMsTextService(scrapeService *ScrapeService, redisService *RedisService) *LLMsTextService {
	return &LLMsTextService{
		scrapeService: scrapeService,
		redisService:  redisService,
		jobs:          make(map[string]*models.LLMsTextJob),
	}
}

// CreateLLMsTextJob 启动后台生成 llms.txt 任务
func (s *LLMsTextService) CreateLLMsTextJob(ctx context.Context, req *models.GenerateLLMsTextRequest, teamID string) (*models.LLMsTextJob, error) {
	jobUUID, err := uuid.NewV7()
	if err != nil {
		jobUUID = uuid.New()
	}
	jobID := jobUUID.String()

	maxURLs := req.MaxURLs
	if maxURLs <= 0 {
		maxURLs = 20
	}

	job := &models.LLMsTextJob{
		ID:           jobID,
		TeamID:       teamID,
		URL:          req.URL,
		MaxURLs:      maxURLs,
		ShowFullText: req.ShowFullText,
		Cache:        req.Cache,
		Status:       "processing",
		CreatedAt:    time.Now(),
		ExpiresAt:    time.Now().Add(24 * time.Hour),
	}

	s.jobsLock.Lock()
	s.jobs[jobID] = job
	s.jobsLock.Unlock()

	go s.runGenerate(job, req)

	return job, nil
}

// GetLLMsTextJob 获取 llms.txt 生成任务状态
func (s *LLMsTextService) GetLLMsTextJob(jobID string) (*models.LLMsTextJob, bool) {
	s.jobsLock.RLock()
	defer s.jobsLock.RUnlock()
	job, exists := s.jobs[jobID]
	return job, exists
}

// runGenerate 执行站点扫描并生成标准 llms.txt 与 llms-full.txt
func (s *LLMsTextService) runGenerate(job *models.LLMsTextJob, req *models.GenerateLLMsTextRequest) {
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	log.Info().Str("jobID", job.ID).Str("url", job.URL).Msg("开始后台生成 llms.txt")

	// 抓取主页
	doc, err := s.scrapeService.ExecuteScrape(ctx, &models.ScrapeRequest{
		URL:     job.URL,
		Formats: []string{"markdown"},
	}, job.ID)

	var title string = job.URL
	var content string = ""
	if err == nil && doc != nil {
		if doc.Metadata.Title != "" {
			title = doc.Metadata.Title
		}
		content = doc.Markdown
	}

	// 构造标准 llms.txt
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# %s\n\n", title))
	sb.WriteString(fmt.Sprintf("> Generated by Firecrawl for %s\n\n", job.URL))
	sb.WriteString("## Documentation & Overview\n")
	sb.WriteString(fmt.Sprintf("- [%s](%s): Main documentation and overview.\n\n", title, job.URL))

	job.GeneratedTxt = sb.String()

	if job.ShowFullText {
		var fullSb strings.Builder
		fullSb.WriteString(job.GeneratedTxt)
		fullSb.WriteString("\n## Full Documentation Content\n\n")
		fullSb.WriteString(content)
		job.FullTxt = fullSb.String()
	}

	job.Status = "completed"
	log.Info().Str("jobID", job.ID).Msg("llms.txt 生成完成")
}
